version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - ./postgres/dbfiles:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres
    networks:
      - net
    ports:
        - 9090:8080

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    networks:
      - net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: hotel
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
      - adminer

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - net
    volumes:
      - /node_modules
    depends_on:
      - backend

  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
    depends_on:
      - postgres
      - adminer
    networks:
      - net
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: qwerty
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/temp:/opt/sonarqube/temp
      - ./sonarqube/conf:/opt/sonarqube/conf

  jenkins:
    image: jenkins/docker
    build:
      context: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - net
    container_name: jenkins
    depends_on:
      - sonarqube
      - adminer
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  net:

volumes:
  postgres_dbfiles:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonarqube_conf:
  jenkins_home: