# Generated by Django 4.2.11 on 2024-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                ("calle", models.CharField(max_length=50, verbose_name="Calle")),
                ("numero", models.IntegerField(verbose_name="Número dirección")),
                ("comuna", models.CharField(max_length=50, verbose_name="Comuna")),
                ("telefono", models.IntegerField(verbose_name="Número telefonico")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo eléctronico"
                    ),
                ),
            ],
        ),
    ]
