# Generated by Django 4.2.11 on 2024-03-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(verbose_name="Número de la habitación")),
                (
                    "ocupado",
                    models.CharField(
                        choices=[("si", "Si"), ("no", "No")],
                        max_length=2,
                        verbose_name="Ocupada",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.hotel",
                        verbose_name="Hotel",
                    ),
                ),
            ],
        ),
    ]
